#!/usr/bin/env zsh

BASEDIR="${0:a:h}"

echo "Linking dotfiles..."

link_file() {
  ln -sf $BASEDIR/$1 ~/.$1
}

link_dir() {
  ln -shf $BASEDIR/$1 ~/.$1
}

# Oh my zsh, p10k and basic shell configs
link_file zshrc
link_file aliases
link_file p10k.zsh
link_file keybindings

# Git
link_file gitignore_global
link_file gitconfig_global
git config --global include.path ~/.gitconfig_global

# Shhh
touch secrets
link_file secrets

# asdf
link_file asdfrc
link_file default-npm-packages
link_file default-python-packages

# Everything else
touch extra
link_file extra

# iTerm2 preferences setup
link_dir iterm2

# nano
echo "include $(brew --prefix nanorc)/share/nanorc/*.nanorc" > nanorc
link_file nanorc

echo "Setting macOS defaults..."
# Set iTerm2 preferences
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.iterm2"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Auto-hide dock
defaults write com.apple.dock autohide -bool true

# Enable 3 finger drag
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool true

# Enable tap to click on the trackpad
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

# Allow Tab key to access all controls
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Speed up key repeat and reduce delay
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Show develop menu on Safari
defaults write com.apple.Safari.SandboxBroker ShowDevelopMenu -bool true

echo "Finished. A system reboot is recommended at this time."
